# Generated by Django 4.1.5 on 2023-01-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gastronomia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('ingredientes', models.CharField(max_length=128)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Paisajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('estados', models.CharField(max_length=128)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Turismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('comidas', models.CharField(max_length=128)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
