# Generated by Django 4.1.5 on 2023-01-31 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vzla', '0002_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='turismo',
            name='fecha_limite',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='turismo',
            name='paisajes',
            field=models.CharField(default='sin datos', max_length=128),
            preserve_default=False,
        ),
    ]
