# Generated by Django 4.1.5 on 2023-02-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vzla', '0003_turismo_fecha_limite_turismo_paisajes'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastronomia',
            name='imagen',
            field=models.ImageField(default='sin dato', upload_to='Gastro/'),
            preserve_default=False,
        ),
    ]
