# Generated by Django 4.1.5 on 2023-02-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vzla', '0004_gastronomia_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='paisajes',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='paisaje'),
        ),
        migrations.AddField(
            model_name='turismo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='turismo'),
        ),
        migrations.AlterField(
            model_name='gastronomia',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='gastro'),
        ),
    ]
