# Generated by Django 4.1.5 on 2023-02-01 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vzla', '0005_paisajes_imagen_turismo_imagen_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paisajes',
            old_name='imagen',
            new_name='imagen_p',
        ),
    ]
