# Generated by Django 4.1.5 on 2023-02-01 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vzla', '0006_rename_imagen_paisajes_imagen_p'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paisajes',
            old_name='imagen_p',
            new_name='imagen',
        ),
    ]
